### ISSUE TITLE
feature request: print parse probability

### ISSUE THREAD

**Issue by jowagner** [CNGLDLab/LORG-Release#5]
add option to print parse probability as in --verbose (but without all the other details)

**Comment by jihelhere** [comment]
Hello Joakim,

I don't know who's in charge of this repository but I got an email so... it must be me ;)

I will not update it anymore (too old code, difficult to maintain and prove correct, etc...).
Please see my 'new' repo/fork https://github.com/jihelhere/LORG-Release
In particular, there is  a json\* output, maybe this is something you might like

Cheers,
